# A Beginner's guide to Pytorch

**PyTorch** is an open source machine learning library. It is mainly used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research Lab. PyTorch performs computations on *Tensors*.

**Tensor**: Tensors are nothing but multi-dimensional arrays similar to that in NumPy arrays. The main difference and advantage of tensors is that the tensors and its related operations can run on a CPU or GPU.

Let us look at some basic tensor operations to get started with Pytorch:

- tensor
- rand
- zeros
- arange
- eye

Let us begin by importing `torch` and listing out the functions covered in this notebook.

In [37]:
# Installing `torch` library and `numpy`
!pip install torch --quiet
!pip install numpy --upgrade --quiet

In [38]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.tensor

This is the starting point function to learn for PyTorch. This function is used to create tensors from a python list or NumPy array which is passed as the parameter to this function. Let us look at some examples to get a better understanding:

In [39]:
# Example 1 
list1 = [1, 2, 3, 4] # Initializing a python list
t1 = torch.tensor(list1) # Converting the list to tensor

In the above example, `list1` is Python list which is being converted to a PyTorch tensor using the `torch.tensor()` function. We can verify the types of the same:

In [40]:
print(type(list1))
print(type(t1))

<class 'list'>
<class 'torch.Tensor'>


Let us now initialize a NumPy array and then convert it to PyTorch tensor

In [6]:
# Example 2
array_1 = np.array([[1,2],[10.0,11]])
t2 = torch.tensor(array_1)
t2

tensor([[ 1.,  2.],
        [10., 11.]], dtype=torch.float64)

In the above example, `array_1` is a NumPy array which is being converted to a PyTorch tensor using `torch.tensor()` function. A point to observe is that there is only one float value in the numpy array but the entire array is being converted to float values because of that. 

We can verify the types of `array_1` and `t2`:

In [7]:
print(type(array_1))
print(type(t2))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


There is also another function `torch.from_numpy()` which takes a numpy array as parameter and converts it into a Pytorch tensor.

In [32]:
# Example 3
array_2 = np.array([[1,2],[3,4]])
torch.from_numpy(array_2)

tensor([[1, 2],
        [3, 4]])

In [33]:
# Example 4
torch.tensor([[1, 2], [3, 4, 5]])

ValueError: expected sequence of length 2 at dim 1 (got 3)

In the above example, it can be seen that the `torch.tensor()` is not being able to convert the given 2D numpy array to a tensor as the 2D array is uneven for which it cannot convert the array to a tensor.

`torch.tensor()` is a basic function used as a starting point of the process for any project to convert the data into tensors to work with.

## Function 2 - torch.rand()

This is one of the important functions and used quite often in PyTorch. It is used to intialize the tensor with random numbers with the give shape.

Let us look at some examples to get a better understanding of this function:

In [9]:
# Example 1
torch.rand(6)

tensor([0.3686, 0.0077, 0.8398, 0.0438, 0.6749, 0.4669])

In the above example, we can observe that a tensor has been initialized or filled with random values between 0 and 1 with 6 columns and 1 row.

In [10]:
# Example 2 
torch.rand(3,4)

tensor([[0.6974, 0.1860, 0.7828, 0.4290],
        [0.7740, 0.3860, 0.6311, 0.0440],
        [0.0578, 0.8943, 0.4333, 0.5459]])

In the above example, we can observe a 2D tensor has been initialized with random values between 0 and 1 with the shape specified in the parameters i.e. 3X4. 

Similarly, this function can be used to generate a tensor of any dimension

In [41]:
# Example 3 
torch.rand(3,4,6,2)

tensor([[[[0.1083, 0.6528],
          [0.4287, 0.1184],
          [0.0530, 0.1038],
          [0.0605, 0.3506],
          [0.2933, 0.0248],
          [0.4065, 0.9458]],

         [[0.8977, 0.7638],
          [0.6217, 0.5297],
          [0.6944, 0.2822],
          [0.4618, 0.7407],
          [0.3553, 0.3659],
          [0.0715, 0.1856]],

         [[0.3099, 0.9973],
          [0.7081, 0.4504],
          [0.4313, 0.2807],
          [0.7381, 0.8840],
          [0.7114, 0.9964],
          [0.8124, 0.1385]],

         [[0.2123, 0.5982],
          [0.9496, 0.1864],
          [0.1517, 0.4581],
          [0.2669, 0.7094],
          [0.8998, 0.1319],
          [0.7037, 0.9070]]],


        [[[0.3796, 0.9582],
          [0.6449, 0.3931],
          [0.7885, 0.7058],
          [0.8423, 0.4977],
          [0.1235, 0.0961],
          [0.4686, 0.5435]],

         [[0.8960, 0.2768],
          [0.1099, 0.2665],
          [0.1996, 0.8921],
          [0.6958, 0.3728],
          [0.3508, 0.9933],
        

In the above example, we can observe that a 4 Dimensional tensor has been initialized with random values between 0 and 1. It is hard to visualize this but the process is very simple.

The `torch.rand()` is a very useful function particularly during the weights and bias iniatilization in machine learning with random values.

## Function 3 - torch.zeros()

This function is used to create a PyTorch tensor and fill with zeros with the shape of tensor passed as parameters. 

Let us look at some examples to get a better understanding of this function:

In [42]:
# Example 1

torch.zeros(3)

tensor([0., 0., 0.])

In the example above, we can see that a tensor of shape 1X3 is being created with all zeros in the tensor. 

Tensors of various dimensions can be created using the same process

In [43]:
# Example 2 

torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In the above example we are creating a Pytorch tensor with 2X3 dimension completely initialized with 0's.

This process is similar to another function `torch.ones()` where it creates a tensor completely filled with 1's. Let us look at one example to get a better understanding of this function too:

In [14]:
# Example 3

torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In the above example, a pytorch tensor with dimension 3X5 is being created which is completely filled with 1's. This is similar to the `torch.zeros()` function that we have looked earlier.

These functions can be very useful to build machine learning and deep learning algorithms when we have to use an array completely filled with 0's or 1's.

## Function 4 - torch.arange()

This function gives us a 1-Dimensional tensor with values ranging from \[start,end). `start` and `end` are passed as parameters to the function. There is another parameter `step` that we can pass as a parameter to the function to indicate the absolute difference between two consecutive values in the tensor i.e. they are equally spaced. Therefore, the shape of the tensor generated would be (end-start)/step

To have a better understanding of this function, let us look at some examples:

In [15]:
# Example 1

torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In the example above, `start=1` and `end=10` which is initializing a tensor with values starting from 1 to 9.

In this example, we did not specify any value for `step` parameter. By default, `step=1`. Therefore, we have got the tensor values with a common difference of 1.

In [16]:
# Example 2 
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In the above example, only one parameter is passed which by default is `end=5`. Therefore, the tensor is initialized with values from 0 to 4. Here, `start=0` which is set by default.

The function doesn't work if no parameters are passed to it.

In [44]:
# Example 3 
torch.arange(1,5,.5)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])

In the above example, the `step=0.5` parameter is also passed along with `start=1` and `end=5` which is why the tensor is generated with the length of 10 and common difference between every two elements in 0.5 

This function can be very used to quickly generate values from one number to another in a sequential order with any common difference between elements.

## Function 5 - torch.eye()

This function is used to generate a tensor with 1's in the diagonal and 0's elsewhere i.e. identity matrix of shape N X M where N,M are passed as parameters to this function.

Let us look at some examples to get a better understanding of this function.

In [45]:
# Example 1
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In the example above, we can observe that a tensor of shape 3X3 is generated which is an identity matrix consisting of 1's in the diagonal and 0's elsewhere.

*Note:* Although we did not pass two parameters, the function is considering `N=M=3`.

In [24]:
# Example 2 
torch.eye(3,2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])

In the example above, the dimension passed as parameters are `N=3` and `M=2` which is not a square matrix shape but the function is generating a tensor of shape 3X2 which is also an identity matrix.

In [27]:
# Example 3
torch.eye(3,2,1)

TypeError: eye() received an invalid combination of arguments - got (int, int, int), but expected one of:
 * (int n, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (int n, int m, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In the example above, we can observe that the function only works if we pass either 1 or 2 parameters but not more. This is the case where this function returns an error.

Identity matrices are very frequently used in applications like computer vision and deep learning.

## Conclusion

In the above notebook, we have understood what Pytorch is and some basic functions in Pytorch which are used very frequently in many applications.

## Reference Links
Links for reference and other interesting articles and functions in Pytorch:
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html